baseurl: https://keen-noether-7d2e44.netlify.app/
languageCode: en-us
title: Rob Wiederstein - a blog about coding, data and public policy
theme: hugo-lithium
author: Rob Wiederstein
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: CV
      url: /cv/
    - name: Datasets
      url: /datasets/
    - name: Gallery
      url: /gallery/
    - name: Recipes
      url: /recipe/
params:
  author: Rob Wiederstein
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website about data, analysis, and public policy.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - go
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
#og: tags
  images:
    - images/site/site-cover-fb-1200-630px.jpg
  site_name: Rob Wiederstein | a blog about coding, data and public policy
taxonomies:
  category: categories
  tag: tags
canonifyURLs: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: github
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
