baseurl: https://keen-noether-7d2e44.netlify.app/
languageCode: en-us
title: Rob Wiederstein -- a blog about data
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: CV
      url: /cv/
    - name: Datasets
      url: /datasets/
    - name: Gallery
      url: /gallery/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website about data, analysis, and public policy.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
#og: tags
  images:
    - image/site/site-profile-fb-1200-630px.jpg
  title: My cool site
taxonomies:
  series: series
canonifyURLs: false

